import os
import numpy as np


class vadereOutputLoader:
    """This class load the data output by "KNearestNeighborProcessor" from Vadere. 
    """
    def __init__(self, dataset_folder_path, processed_output_path=None):
        self.dataset_folder_path = dataset_folder_path
        self.processed_output_path = processed_output_path
        if self.processed_output_path is None:
            self.processed_output_path = dataset_folder_path
    
    def process_rowdata(self, dataset_name, numOfCols):
        """Given the data file directly generated by Vadere, this method will do the followings:
        Rows containing information of pedestrians outside the measurement area will be omitted.
        Rows containing information of pedestrians that have less than K neighbors will be omitted.

        The processed data would have the format:

            timeStep | pedID | pedVelocity | meanSpacingDistance (optional) | relative-coordinates-of-KNN (contains K*2 columns)

        The processed dataset will be output to the output folder with the name "processed_datasetname".

        Args:
            dataset_name (str): name of the dataset file in the dataset folder, e.g. "trial_data.txt"
            numOfCols (int): number of columns in the format mentioned above
        """
        dataset_path = os.path.join(self.dataset_folder_path, dataset_name)
        output_path = os.path.join(self.processed_output_path, "processed_"+dataset_name)

        rowID = -1
        with open(dataset_path, "r") as input, open(output_path, "w") as output:
            row = input.readline()
            output.write(row)
            while True:
                rowID += 1
                tmp_row = row.split()
                if len(tmp_row) == numOfCols:
                    output.write(row)
                row = input.readline()
                if not row:
                    break

    def loadData(self, dataset_name, numOfNeighbours, need_processing = True, contain_sk = True):
        """Load the dataset from vadere. Preprocess the dataset if it need processing.

        Args:
            dataset_name (str): name of the dataset file in the dataset folder.
            numOfNeighbours (int): number of nearest neighbours
            need_processing (bool, optional): whether the given dataset need processing. Defaults to True.
            contain_sk (bool, optional): whether the given dataset contains the column mean spacing distance sk. Defaults to True.

        Returns:
            numpy.ndarray: the loaded and processed dataset
        """
        numOfCols = 4 + 2*numOfNeighbours
        if not contain_sk:
            numOfCols -= 1

        if need_processing:
            self.process_rowdata(dataset_name, numOfCols)
            dataset_path = os.path.join(self.processed_output_path, "processed_"+dataset_name)
        else:
            dataset_path = os.path.join(self.dataset_folder_path, dataset_name)

        vadereRawdata = np.loadtxt(dataset_path, delimiter=" ", skiprows=1)
        

        return vadereRawdata